method: bayes
program: train.py
metric:
  goal: maximize
  name: val/max
name: event_sweep_complex54
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--log-wandb"
  - ${args}
parameters:
  data-path:
    value: /data/rboone/datasets/wg_dvst
  dS-du:
    value: Gamma
  du-du:
    value: complex54
  experiment:
    value: "event_sweep_complex54_1_18"
  model:
    value: "max_former"
  config:
    value: ./event_sweepcfile.yaml
  epochs:
    value: 50
  snnbp-alpha:
    distribution: log_uniform_values
    max: 100.0
    min: 0.1
  snnbp-beta:
    distribution: log_uniform_values
    max: 100.0
    min: 0.1
  snnbp-epsilon:
    distribution: log_uniform_values
    max: 1.0
    min: 0.05
  snnbp-p:
    distribution: log_uniform_values
    max: 50.0
    min: 1.0
  snnbp-tau:
    value: 0.5
  lr:
    distribution: log_uniform_values
    max: 0.05
    min: 0.0001
  weight-decay:
    distribution: log_uniform_values
    max: 0.1
    min: 0.0001
