method: bayes
program: train.py
metric:
  goal: maximize
  name: val/max
name: complex54_fixed_test
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--log-wandb"  # <--- Triggers the store_true flag
  - ${args}
parameters:
  data-path:
    value: /data/rboone/datasets/cifar10/
  dS-du:
    value: Gamma
  du-du:
    value: complex54
  experiment:
    value: "cifar10_sweep_complex54"
  model:
    value: "max_former"
  config:
    value: ./cifar10_sweepcfile.yaml
  epochs:
    value: 50
  lr:
    distribution: log_uniform_values
    min: 1e-4
    max: 5e-3
  weight-decay:
    distribution: log_uniform_values
    min: 1e-4
    max: 1e-1
  snnbp-alpha:
    distribution: log_uniform_values
    min: 0.1
    max: 20.0
  snnbp-beta:
    distribution: log_uniform_values
    min: 0.1
    max: 20.0
  snnbp-epsilon:
    distribution: log_uniform_values
    min: 0.01
    max: 0.5
  snnbp-p:
    distribution: uniform
    min: 0.5
    max: 10.0
early_terminate:
  type: hyperband
  min_iter: 15
  eta: 3