epochs: 400
time_step: 4
layer: 4
dim: 384
num_heads: 12
patch_size: 4
mlp_ratio: 4

# Updated with the path from your successful runs
data_path: '/data/rboone/datasets/cifar10/'
dataset: torch/cifar10
num_classes: 10
img_size: 32
mean:
    - 0.4914
    - 0.4822
    - 0.4465
std:
    - 0.2470
    - 0.2435
    - 0.2616
crop_pct: 1.0
scale:
    - 1.0
    - 1.0
ratio: [1.0,1.0]
color_jitter: 0.
interpolation: bicubic
train_interpolation: bicubic
aa: rand-m9-n1-mstd0.4-inc1
mixup: 0.5
mixup_off_epoch: 200
mixup_prob: 1.0
mixup_mode: batch
mixup_switch_prob: 0.5
model: max_former
cutmix: 0.5
reprob: 0.25
remode: const
amp: True
batch_size: 128
val_batch_size: 128

# Best hyperparameters from Sweep Run 1
lr: 0.004479767587025382
weight_decay: 0.03636769062667741

# Gradient & SNNBP settings from Sweep Run 1
du_du: conservative_cgrad
dS_du: Gamma
snnbp_alpha: 1.209609390718007
snnbp_beta: 1.3665607164533111
snnbp_decay: 0.6053235214358093
snnbp_epsilon: 0.35743030342249227
snnbp_intervention: 0.5319400634485713
snnbp_k_dir: 1.710829237696388
snnbp_max_ratio: 1.9208628645125947

min_lr: 1e-5
sched: cosine
cooldown_epochs: 10
warmup_epochs: 20
warmup_lr: 0.00008
opt: adamw
smoothing: 0.1
workers: 4
# seed: 50425
use_custom_neuron: True